defaults:
  - model: deepspeech2
  - metrics: example
  - datasets: inference
  - dataloader: example
  - transforms: example
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predict"
  seed: 1
  from_pretrained: "data/main_models/model_best.pth" # path to the pretrained model
